# Generated by Django 4.1.3 on 2022-12-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='classification',
            field=models.CharField(default='waiting for classification', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
